services:
  mysql:
    image: mysql:8.4
    restart: always
    container_name: mysql-nlw
    environment:
      - MYSQL_ROOT_PASSWORD=Fprp1157.#
    ports:
      - '3336:3336'
    networks:
      - my-network
networks:
  my-network:
    driver: bridge